export const IS_TYPING = 'IS_TYPING'
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const USER_TOKEN = 'USER_TOKEN'
export const CURRENT_USER = 'CURRENT_USER'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const CHECK_CONNECTION = 'CHECK_CONNECTION'
export const RESET = 'RESET'


export const SAVE_DATA = 'SAVE_DATA'
export const SAVING_FAILED = 'SAVING_FAILED'
export const SAVING_SUCCESS = 'SAVING_SUCCESS'


export const NAME_CHANGED = 'NAME_CHANGED'
export const GENDER_CHANGED = "GENDER_CHANGED"
export const IMAGE_CHANGED = 'IMAGE_CHANGED'
export const COMPLETED = 'COMPLETED'


export const ADD_MESSAGE = 'ADD_MESSAGE'
export const START_FETCH_MESSAGES = 'START_FETCH_MESSAGES'
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const RECIEVE_MESSAGE = 'RECIEVE_MESSAGE'
export const RETREVE_MESSAGES = 'RETREVE_MESSAGES'